[package]
name = "pommel"
version = "0.1.1"
edition = "2024"

[dependencies]
decent = { git = "https://github.com/Cerulity32K/decent" }
decent-macros = { git = "https://github.com/Cerulity32K/decent" }
